#!/bin/sh
#
# Overlayfs snapshot management script
#
#-----------------------------------------------------------------------
#
# Copyright (C) 2016 CTERA Networks. All Rights Reserved.
# Author: Amir Goldstein <amir73il@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

SCRIPT_NAME=$(basename $0)
SCRIPT_VER=0.1
FSTYPE=overlay
SCRIPT_DESC="$FSTYPE snapshot management script"
CMD="$1"
ARGS="$*"

RED='\033[1;31m'
GREEN='\033[1;32m'
ORANGE='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color
ABORTED="${RED}ABORTED${NC}"
ERROR="${RED}ERROR:${NC}"
WARN="${ORANGE}WARN:${NC}"
INFO="${BLUE}INFO:${NC}"
OK="${GREEN}OK${NC}"

trap "abort" 0 1 2 3 15
abort()
{
	rc=$?
	[ $rc != 0 ] || return
	echo "$SCRIPT_NAME $ARGS: $ABORTED"
	exit $rc
}

ok()
{
	echo "$SCRIPT_NAME $ARGS: $OK"
}

error()
{
	echo "$SCRIPT_NAME: $CMD: $ERROR $1" >&2
	exit 1
}

warn()
{
	echo "$SCRIPT_NAME: $CMD: $WARN $1"
}

info()
{
	echo "$SCRIPT_NAME: $CMD: $INFO $1"
}

version()
{
	echo "$SCRIPT_NAME v$SCRIPT_VER ($SCRIPT_DESC)"
}

usage()
{
	version
	echo "usage: $SCRIPT_NAME help [cmd]"
	echo "usage: $SCRIPT_NAME version"
	echo "usage: $SCRIPT_NAME debug"
	echo
	echo "$FSTYPE snapshot commands:"
	echo "usage: $SCRIPT_NAME {status|list}  [<path>|-a]"
	echo "usage: $SCRIPT_NAME {umount|mount} [<path>|-a]"
	echo "usage: $SCRIPT_NAME {create|take}  <path>[@[/]<snapshot-name>] (default-name=<date.time>)"
	echo "usage: $SCRIPT_NAME {delete|remove} <path>@[/]<snapshot-name>"
	echo "usage: $SCRIPT_NAME {clean}         <path>"
	echo
	echo "snapshot command parameter may be given in ZFS style <path>@<snapshot-name>"
        echo "and it may be given as the snapshot directory path <path>@/<snapshot-name>."
	echo "If <snapshot-name> part is omitted, command may apply to all snapshots (e.g. umount)."
	echo
	echo "$FSTYPE snapshot test commands:"
	echo "usage: $SCRIPT_NAME {test|tests} <path> [test-number] [file-size-mb]"
	echo "usage: $SCRIPT_NAME {check}      <path>[@[/]<snapshot-name>]"
	echo
	exit $1
}

debug()
{
	set -- $(mount -t debugfs)
	[ $# -ne 0 ] || error "debugfs not mounted?"
	local dd="$3/dynamic_debug/control"
	[ -f $dd ] || error "CONFIG_DYNAMIC_DEBUG not enabled in kernel?"
	echo "file fs/overlayfs/snapshot.c  +p" > $dd
}

# parse <path>[[/]@[/]<snapshot-name>] argument
parse_path_snapshot_arg()
{
	set -- $( IFS=@; echo $1 )
	# strip / from <path>/ and /<snapshot-name>
	MNT=${1%/}
	snap=${2#/}
	# directory inside <path> to store snapshot related files
	SNAPDIR=$MNT@
	# directory prefix for snapshot mount points
	# snaphot mount points will be created as $SNAPROOT/<snapshot-name>/_
	SNAPROOT=$MNT@
	SNAPMNT=$SNAPROOT/_
	# file to store snapshots stack
	SNAPSHOTS="$SNAPDIR/.snapshots"

	# list|status and mount|umount commands can take -a instead of <path> argument
	if [ "$CMD" = list -o "$CMD" = status -o "$CMD" = mount -o "$CMD" = umount ] && \
		[ "$MNT" = "-a" ]; then
		return
	fi
	[ -n "$MNT" ] || usage 1
	[ -d "$MNT" ] || error "'$MNT' is not a directory!"
	mkdir -p $SNAPMNT || error "creating snapshot mount point"
	export MNT
	S=$MNT@$snap
	SNAPTEST="ovlsnaptest"
	TESTDIR="$SNAPMNT/$SNAPTEST"
	BACKUPDIR="$TESTDIR.bak"
}

current_snapshot()
{
	[ -s $SNAPSHOTS ] || return
	tail -n 1 $SNAPSHOTS
}

oldest_snapshot()
{
	[ -s $SNAPSHOTS ] || return
	head -n 1 $SNAPSHOTS
}

snapshot_is_current()
{
	[ -n "$1" ] && [ "$1" = $(current_snapshot) ]
}

snapshot_is_oldest()
{
	[ -n "$1" ] && [ "$1" = $(oldest_snapshot) ]
}

snapshot_in_stack()
{
	[ -s $SNAPSHOTS ] && grep -q "^$1$" $SNAPSHOTS
}

snapshot_is_deleted()
{
	[ ! -d $SNAPDIR/$1/_ ]
}

snapshot_exists()
{
	local s=$1

	if [ -z "$s" ]; then
		# Does any snapshot exist?
		[ -s $SNAPSHOTS ]
	else
		# Does snapshot $s exist?
		[ -d $SNAPDIR/$s ] || snapshot_in_stack $s
	fi
}

create_snapshot()
{
	local s=$1

	mkdir -p $SNAPDIR/$s/u || exit 1
	mkdir -p $SNAPDIR/$s/w || exit 1
	mkdir -p $SNAPDIR/$s/_ || exit 1
	mknod $SNAPDIR/$s/u/@ c 0 0 || exit 1
	echo $s >> $SNAPSHOTS || exit 1
	sync
}

delete_snapshot()
{
	local s=$1

	umount -i $SNAPDIR/$s/_ 2>/dev/null
	rm -rf $SNAPDIR/$s/w || exit 1
	rm -rf $SNAPDIR/$s/_ || exit 1
	sync
}

remove_snapshot()
{
	local s=$1

	umount -i $SNAPDIR/$s/_ 2>/dev/null
	rm -rf $SNAPDIR/$s || exit 1
	grep -v "^$1$" $SNAPSHOTS > $SNAPSHOTS.tmp
	sync
	mv $SNAPSHOTS.tmp $SNAPSHOTS
	sync
}

remove_all_snapshots()
{
	umount -i $SNAPDIR/*/_ 2>/dev/null

	[ ! -s $SNAPSHOTS ] || mv $SNAPSHOTS $SNAPSHOTS.clean

	# Remount snapshot mount '-o nosnapshot' so we can cleanup
	remount_snapshot

	[ -e $SNAPSHOTS.clean ] || return
	for s in `cat $SNAPSHOTS.clean`; do
		rm -rf $SNAPDIR/$s || exit 1
		echo "snapshot $MNT@$s was removed"
	done
	rm $SNAPSHOTS.clean
	sync
}

snapshot_is_mounted()
{
	local s=$1

	if [ -z "$s" ]; then
		grep -q "^\S\+ $SNAPMNT snapshot" /proc/mounts
	else
		grep -q "^\S\+ $SNAPROOT/$s/_ overlay" /proc/mounts
	fi
}

mount_snapshot()
{
	! snapshot_is_mounted || return
	mount -t snapshot $MNT $SNAPMNT || exit 1
}

umount_snapshot()
{
	snapshot_is_mounted || return
	umount $SNAPMNT || exit 1
}

remount_snapshot()
{
	snapshot_is_mounted || return
	# remount with -osnapshot=$(current_snapshot)
	mount $SNAPMNT -o remount || exit 1
}

umount_all_mounted_snapshots()
{
	mount -t snapshot | ( while read dev on path opt; do
		$0 umount "$path" || warn "failed to umount snapshot at $path"
	done )
}

snapshot_du()
{
	du -hs "$SNAPDIR/$1/u" 2>/dev/null | \
		( read a b &&  echo $a )
}

list_snapshots()
{
	echo "Snapshots list at '$MNT':"
	echo "-------------------------"
	echo "* = current, M = mounted, D = deleted"
	echo
	echo "Status Name\tDisk-usage"
	echo "--------------------------"
	for s in $( tac $SNAPSHOTS ) ; do
		current=" "
		status=" "
		if snapshot_is_deleted $s ; then
			status="D"
		fi
		if snapshot_is_mounted $s ; then
			status="M"
		fi
		if snapshot_is_current $s ; then
			current="*"
		fi
		echo "$current$status     $s\t$(snapshot_du $s)"
	done
}

list_snapshot_mounts()
{
	local s=$1

	mount -t snapshot | ( while read dev on path opt; do
		[ -z "$s" ] || [ "$s" = "$path" ] || continue
		echo "$dev on $path"
	done )
}

list_all_mounted_snapshots()
{
	mount -t snapshot | ( while read dev on path opt; do
		$0 list "$path" || warn "failed to list snapshot at $path"
	done )
}

show_all_mounted_snapshots()
{
	mount -t snapshot | ( while read dev on path opt; do
		echo "$dev on $path $opt"
		echo "\\"
		path="${path%_}"
		mount | grep " on $path.*/_ type"
		echo .
	done )
}

snapshot_status()
{
	if ! snapshot_exists ; then
		info "No $FSTYPE snapshots at '$MNT'"
		return 1
	fi

	S=$MNT@$(current_snapshot)
	if snapshot_is_mounted ; then
		info "$FSTYPE snapshot $S is mounted"
	else
		info "$FSTYPE snapshot $S is not mounted"
	fi

	echo
	echo -n "$MNT filesystem disk usage: "
	df -h $MNT | tail -n 1 | \
		( read d t u f p m && echo "$u $f $p" )
	echo -n "$MNT directory  disk usage: "
	du -hs -x --exclude=@ "$MNT" | \
		( read u m && echo "$u" )
	echo -n "$MNT snapshots  disk usage: "
	du -hs -x "$SNAPDIR" | \
		( read u m && echo "$u" )
}

# Global commands that take no <path>[@<snapshot>] argument
case "$CMD" in
  ''|help)
	[ -n "$2" ] || usage 0
	# help <cmd> => <cmd> help
	exec "$0" "$2" help
	;;
  version)
	if [ "$2" = help ]; then
		echo "version: display $SCRIPT_NAME version."
		exit 0
	fi
	version
	exit 0
	;;
  debug)
	if [ "$2" = help ]; then
		echo "debug: enable kernel debug prints."
		exit 0
	fi
	debug && ok
	exit 0
	;;
esac

mktest()
{
	local d

	for d in A B C D E; do
		mkdir -p $TESTDIR/$d || return 1
	done
	echo aligator > $TESTDIR/A/a.txt && \
		echo bizon > $TESTDIR/B/b.txt && \
		echo camel > $TESTDIR/C/c.txt
}

csum()
{
	local f

	cd $TESTDIR > /dev/null
	md5sum ?/* > md5list || return 1
	for f in $( ls *M.? 2> /dev/null ) ; do
		md5sum $f || return 1
	done >> md5list
	cd - > /dev/null
}

cptest()
{
	local s=$1
	local d=$TESTDIR
	local b=$BACKUPDIR/$s
	local f

	mkdir -p $b || return 1
	[ -d $d ] || return 1

	csum || return 1
	for f in A B C D E md5list; do
		cp -a $d/$f $b/ || return 1
	done
}

lstest()
{
	local s=$1
	local d=$TESTDIR
	local b=$BACKUPDIR/$s
	local f

	if [ -n "$s" ]; then
		echo Files in snapshot $s:
		d=$SNAPROOT/$s/_/$SNAPTEST
		[ -d $d ] || error "no test files in snapshot $s"
		[ -d $b ] || error "no backup files for snapshot $s"
		for f in A B C D E md5list; do
			diff -qr $b/$f $d/$f || error "wrong files in snapshot $s"
		done
	else
		echo Files in snapshot mount:
		[ -d $d ] || return
	fi

	cd $d > /dev/null
	grep "" ?/* 2>/dev/null
	echo .
	if [ -s md5list ]; then
		md5sum -c md5list || error "wrong checksum in snapshot"
	fi
	cd - > /dev/null
	echo .
}

# Snapshot commands that take <path>[@<snapshot>] argument
[ "$2" = help ] || parse_path_snapshot_arg "$2"
case "$CMD" in
  status|list)
	if [ "$2" = help ]; then
		echo "list: display list and status of $FSTYPE snapshots."
		echo "usage: $SCRIPT_NAME {status|list} [<path>|-a]"
		echo
		echo "run '$SCRIPT_NAME list <path>' to list $FSTYPE snapshots at <path>"
		echo "run '$SCRIPT_NAME list -a' to list all mounted $FSTYPE snapshots"
		exit 0
	fi
	if [ "$MNT" = "-a" ]; then
		# List all snapshot mounts
		echo "$FSTYPE snapshot mounts:"
		echo "------------------------"
		list_snapshot_mounts
		echo .
		# List all snapshots overlays of all snapshot mounts
		list_all_mounted_snapshots
		exit 0
	elif snapshot_status ; then
		echo .
		list_snapshots
	fi
	echo .
	;;

  create|take)
	if [ "$2" = help ]; then
		echo "$CMD: create a new snapshot."
		echo "usage: $SCRIPT_NAME {create|take} <path>[@[/]<snapshot-name>] (default-name=<date.time>)"
		exit 0
	fi
	if [ -z "$snap" ] ; then
		# default snapshot-name is <date.time>
		snap=$( date -u +%y%m%d.%H%M%S )
		S=$MNT@$snap
	fi
	if snapshot_exists $snap ; then
		error "snapshot $S already exists!"
	fi

	# For now new snapshot requires umount/mount of all snapshots
	create_snapshot $snap
	remount_snapshot
	info "snapshot $S was created"
	echo .
	;;
  delete)
	if [ "$2" = help ]; then
		echo "delete: umount a snapshot and mark it for deletion."
		echo "any non-mounted snapshot can be marked for deletion"
		echo "but some snapshot deletion is deferred to later time."
		echo "usage: $SCRIPT_NAME delete <path>@[/]<snapshot-name>"
		exit 0
	fi
	[ -n "$snap" ] || usage 1
	if snapshot_is_deleted $snap ; then
		error "snapshot $S already deleted!"
	fi
	if ! snapshot_exists $snap ; then
		error "snapshot $S doesn't exist!"
	fi
	if snapshot_is_current $snap ; then
		error "current snapshot $S cannot be deleted!"
	fi

	delete_snapshot $snap
	info "snapshot $S was deleted"
	echo .
	;;
  remove)
	if [ "$2" = help ]; then
		echo "remove: delete a snapshot permanently."
		echo "this command will fail for active snapshot and snapshots"
		echo "in use by older snapshots. try using the delete command."
		echo "usage: $SCRIPT_NAME remove <path>@[/]<snapshot-name>"
		exit 0
	fi
	[ -n "$snap" ] || usage 1
	if ! snapshot_exists $snap ; then
		error "snapshot $S doesn't exist!"
	fi
	if ! snapshot_is_oldest $snap ; then
		error "non-oldest snapshot $S cannot be removed!"
	fi

	remove_snapshot $snap
	remount_snapshot
	info "snapshot $S was removed"
	echo .
	;;
  clean)
	if [ "$2" = help ]; then
		echo "clean: remove all snapshots."
		echo "usage: $SCRIPT_NAME clean <path>"
		exit 0
	fi
	[ -z "$snap" ] || usage 1
	if ! snapshot_exists ; then
		echo "No $FSTYPE snapshots at '$MNT'."
		exit 0
	fi

	remove_all_snapshots
	info "all snapshots at '$MNT' removed"
	echo .
	;;

  mount)
	if [ "$2" = help ]; then
		echo "mount: mount all $FSTYPE snapshots at <path>."
		echo "usage: $SCRIPT_NAME mount [<path>|-a]"
		echo
		echo "run '$SCRIPT_NAME mount -a' to show all mounted $FSTYPE snapshots"
		exit 0
	fi
	if [ "$MNT" = "-a" ]; then
		# show all snapshot mounts and overlays
		show_all_mounted_snapshots
		exit 0
	fi
	S=$MNT@$(current_snapshot)
	if snapshot_is_mounted; then
		error "snapshot $S is already mounted!"
	fi
	mount_snapshot
	info "snapshot $S was mounted"
	echo .
	;;
  umount)
	if [ "$2" = help ]; then
		echo "umount: unmount all $FSTYPE snapshots at <path>."
		echo "usage: $SCRIPT_NAME umount [<path>|-a]"
		echo
		echo "run '$SCRIPT_NAME umount -a' to unmount all mounted $FSTYPE snapshots"
		exit 0
	fi
	if [ "$MNT" = "-a" ]; then
		# Unmount all snapshot mounts
		umount_all_mounted_snapshots
		exit 0
	fi
	S=$MNT@$(current_snapshot)
	if ! snapshot_is_mounted; then
		error "snapshot $S is not mounted!"
	fi
	umount_snapshot
	info "snapshot $S was unmounted"
	echo .
	;;

# Snapshot sanity tests
  tests)
	if [ "$2" = help ]; then
		echo "tests: run snapshot sanity tests 1..N."
		echo "usage: $SCRIPT_NAME tests <path> [test-number] [file-size-mb]"
		echo "file-size-mb: test file size in mega bytes (default = 1)"
		exit 0
	fi
	N=4
	[ -z "$3" ] || N=$3
	if snapshot_is_mounted; then
		$0 umount $MNT || error "failed to umount snapshots"
	fi
	for s in $( cat $SNAPSHOTS 2> /dev/null ) ; do
		$0 remove $SNAPDIR/$s 2> /dev/null || warn "failed to remove snapshot $s"
	done
	$0 mount $MNT || error "failed to mount snapshots"
	for n in $( seq 0 $N ) ; do
		$0 test $MNT $n $4 || exit 1
	done
	lstest
	for n in $( seq 1 $N ) ; do
		lstest $n
	done
	ok
	echo .
	;;
  test)
	if [ "$2" = help ]; then
		echo "test: run snapshot sanity test N."
		echo "usage: $SCRIPT_NAME test <path> [test-number] [file-size-mb]"
		echo "file-size-mb: test file size in mega bytes (default = 1)"
		exit 0
	fi
	n=1
	[ -z "$3" ] || n=$3
	if [ "$n" = 0 ] ; then
		rm -rf $TESTDIR $BACKUPDIR 2> /dev/null
		exit 0
	fi
	if [ "$n" = 1 ] ; then
		mktest || error "failed to create test files"
	fi
	echo
	echo Running snapshot test $n:
	echo ------------------------
	M=1
	[ -z "$4" ] || M=$4
	F=${M}M
	cd $TESTDIR > /dev/null
	NOTRUNC="conv=notrunc"
	# uncomment the following line to run in-place write tests
	INPLACE=$NOTRUNC
	# uncomment the following line to run direct I/O write tests
	#DIRECT="oflag=direct"
	TRUNCSIZE=4
	echo Appending $F zeros to $F.1 $DIRECT
	# append writes to new allocated blocks
	dd if=/dev/zero bs=1M count=$M of=$F.1 $NOTRUNC oflag=append $DIRECT status=noxfer \
		2>/dev/null || exit 1
	echo Writing $F random data to $n files
	for i in $( seq 1 $n ) ; do
		# 1st rewrite splits reflink extents and allocates new blocks
		dd if=/dev/urandom bs=1M count=$M of=$F.$i $INPLACE status=noxfer \
			2>/dev/null || exit 1
		# subsequent rewrites doesn't change reflink extents
		dd if=/dev/urandom bs=1M count=$M of=$F.1 $INPLACE $DIRECT status=noxfer \
			2>/dev/null || exit 1
	done
	cd - > /dev/null
	echo .
	cptest $n || error "failed to backup test files"
	lstest
	s=$n
	$0 take $SNAPDIR/$s || exit 1
	case "$n" in
	  1)
		echo Create test:
		echo ------------
		echo 'Creating d.txt'
		echo dodo > $TESTDIR/D/d.txt
		echo 'Creating e.txt'
		echo emu > $TESTDIR/E/e.txt
	  ;;
	  2)
		echo Write test:
		echo -----------
		echo 'Writing b.txt (append)'
		echo 'barracuda' >> $TESTDIR/B/b.txt
		echo 'Writing c.txt (truncate)'
		echo 'crocodile' > $TESTDIR/C/c.txt
	  ;;
	  3)
		echo Remove test:
		echo ------------
		echo "Truncating c.txt (to size $TRUNCSIZE)"
		truncate -s $TRUNCSIZE $TESTDIR/C/c.txt
		echo 'Removing d.txt'
		rm $TESTDIR/D/d.txt
	  ;;
	  4)
		echo Restore test:
		echo -------------
		f=1
		echo 'Restoring from snapshot' $f
		rm -rf $TESTDIR/?
		cp -R $SNAPROOT/$f/_/$SNAPTEST/? $TESTDIR/
	  ;;
	esac || exit 1
	echo .
	csum || error "failed to calc checksum of files"
	lstest
	lstest $s
	$0 list $MNT || exit 1
	ok
	echo .
	;;

  check)
	if [ "$2" = help ]; then
		echo "check: verify content of test snapshot."
		echo "usage: $SCRIPT_NAME check <path>[@[/]<snapshot-name>]"
		exit 0
	fi
	lstest $snap
	echo .
	;;
  *)
	usage 1
esac

exit 0
